#!/bin/sh

# M130: Extrusion Velocity Control Mode off
# Example: M110
# Turn off the extrusioin velocity control


halcmd setp VelocityExtrusion.0.status 0
halcmd unlinkp axis.3.motor-pos-cmd
halcmd unlinkp VelocityExtrusion.0.A
halcmd unlinkp hpg.stepgen.03.position-cmd
halcmd net emcmot.03.pos-cmd axis.3.motor-pos-cmd hpg.stepgen.03.position-cmd 
 
exit 0


