#!/bin/sh

# M130: Extrusion Velocity Control Retraction
# Example: M130

isenabled=$(halcmd getp AccVelExtr.0.isenabled)

if [ "$isenabled" = "TRUE" ];then
halcmd setp VelocityExtrusion.0.status 4
else
echo "$isenabled componente velocity extruder disabilitato. Abilitarlo con M111"
#eog /home/linuxcnc/linuxcnc/message/M130.png &
halcmd setp message.m111.trigger 1
halcmd setp message.m111.trigger 0
fi


