#!/bin/sh

# M131: Extrusion Velocity Control Precharge ON
# Example: M131

isenabled=$(halcmd getp AccVelExtr.0.isenabled)

if [ "$isenabled" = "TRUE" ];then
halcmd setp AccVelExtr.0.status 4
else
echo "$isenabled Componente velocity extruder disabilitato. Abilitarlo con M111"
#eog /home/linuxcnc/linuxcnc/message/M130.png &
halcmd setp message.m111.trigger 1
halcmd setp message.m111.trigger 0
fi


