#!/bin/sh
# M151: Extrusion Velocity Control Nozzle linked to XY movements
# Example: M151

isenabled=$(halcmd getp AccVelExtr.0.isenabled)

if [ "$isenabled" = "TRUE" ];then
halcmd setp VelocityExtrusion.0.status 3
else
echo "$isenabled Componente velocity extruder disabilitato. Abilitarlo con M111"
#eog /home/linuxcnc/linuxcnc/message/M130.png &
halcmd setp message.m111.trigger 1
halcmd setp message.m111.trigger 0
fi


