#!/bin/sh
# M151: Extrusion Velocity Control Mode on
# Example: M151
# Turn off the extrusioin velocity control

#halcmd setp hal_pru_generic.pwmgen.00.out.01.value $1
#Connette il nozzle alla posizione comandata della A
halcmd setp VelocityExtrusion.0.status 3
exit 0


